### ISSUE TITLE
CSV writer clarifications

### ISSUE THREAD

**Issue by vkhodygo** [jasmineRepo/JAS-mine-core#22]
@pbronka 

I have a question regarding the following section of the code:

https://github.com/jasmineRepo/JAS-mine-core/blob/fa07b21137cbdd71af841354d2bdf0aa83bd9b3c/microsim-core/src/main/java/microsim/data/ExportCSV.java#L171-L176

I saw your recent comments there and I hope you're familiar enough with this part.

What's the point of adding anything to the buffer here when the file to write to doesn't exist?

**Comment by pbronka** [comment]
> @pbronka
> 
> I have a question regarding the following section of the code:
> 
> https://github.com/jasmineRepo/JAS-mine-core/blob/fa07b21137cbdd71af841354d2bdf0aa83bd9b3c/microsim-core/src/main/java/microsim/data/ExportCSV.java#L171-L176
> 
> I saw your recent comments there and I hope you're familiar enough with this part.
> 
> What's the point of adding anything to the buffer here when the file to write to doesn't exist?

I think the answer lies in the following lines: 
https://github.com/jasmineRepo/JAS-mine-core/blob/fa07b21137cbdd71af841354d2bdf0aa83bd9b3c/microsim-core/src/main/java/microsim/data/ExportCSV.java#L122-L127

So if the file doesn't exist, it is first created and then the bufferWriter writes to it, starting with:
https://github.com/jasmineRepo/JAS-mine-core/blob/fa07b21137cbdd71af841354d2bdf0aa83bd9b3c/microsim-core/src/main/java/microsim/data/ExportCSV.java#L128-L133

Not the best convention, perhaps...
