### ISSUE TITLE
Missing imports in DatabaseUtils in v5.0 

### ISSUE THREAD

**Issue by pbronka** [jasmineRepo/JAS-mine-core#23]
Hi @vkhodygo,

@justin-ven and I tried to use the newest version of JAS-mine core to do some testing but ran into issues with DatabaseUtils. Would you be able to have a look please?

Issue: DatabaseUtils from [MRC-CSO-SPHSU/JAS-mine-core/tree/dev/5.0.0](https://github.com/MRC-CSO-SPHSU/JAS-mine-core/tree/dev/5.0.0) uses SchemaExport and SchemaUpdate in the code (inputSchemaUpdateEntityManger() and getOutEntityManger(String persistenceUnitName) methods) but the imports (import org.hibernate.tool.hbm2ddl.SchemaExport;
import org.hibernate.tool.hbm2ddl.SchemaUpdate) are failing.

**Comment by vkhodygo** [comment]
Hi,

I should warn you it's not in the state for any testing at the moment. You can try, but pick the correct version of `hibernate`.
The database part was extremely outdated and required some serious upgrades. I managed to bump the hibernate version to `5.8.1` or something, but I'm not sure if the code works correctly. 
However, `6.0.1` and later make all this code completely invalid as the API doesn't support this anymore. This part has to be rewritten from scratch I'm afraid.

**Comment by vkhodygo** [comment]
Yes, that was my plan. Unfortunately, I had to work on some other things and it took all my time. I'm on leave next week and I'm going to get back to the database section right after that.

**Comment by vkhodygo** [comment]
Hi @pbronka 

Apologies for the delay, let's get back to our business. What features exactly do you need?  It would be great to see two lists: for required and optional features, respectively.

**Comment by pbronka** [comment]
Hi @vkhodygo,

1. Are you planning to update both JAS-mine core and LABSim so that it works with the new version of JAS-mine core?
2. I think the main thing here would be the update of JAS-mine core to the most current JPA library, which will include a full migration from Javax to Jakarta. This will further require updating of other dependencies and code of JAS-mine core and associated integrations with LABSim.

**Comment by vkhodygo** [comment]
@pbronka 
> Are you planning to update both JAS-mine core and LABSim 

Both, but JAS-mine comes first as a more basic package.

> the most current JPA library

That's my plan, however, I'm not a database expert, so I need you feedback on this one.

**Comment by pbronka** [comment]
> @pbronka
> 
> > Are you planning to update both JAS-mine core and LABSim
> 
> Both, but JAS-mine comes first as a more basic package.

I appreciate that the version 5.0 of JAS-mine core is under development, but when we tried to use it with LABSim, with many updates libraries, we encountered multiple issues that would have to be fix. Therefore, one suggestion would be to start with updating only the JPA libraries (as Justin suggests above) and integrating that update with LABSim, before moving to a new problem. In that way, not only changes can be tested, but development of models can continue with updates libraries. 

> 
> > the most current JPA library
> 
> That's my plan, however, I'm not a database expert, so I need you feedback on this one.

I would suggest the following: taking the last stable version of JAS-mine core which works with LABSim (4.0.11),  updating Hibernate:

`		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>4.1.10.Final</version>
		</dependency>`

to most current version [6.1.1. ](https://mvnrepository.com/artifact/org.hibernate/hibernate-core/6.1.1.Final) and updating any related dependencies and resolving issues that will inevitably come up. Then integrating the new version with LABSim, before moving to a new issue. Does that sound ok?

**Comment by pbronka** [comment]
Hi @vkhodygo ,

Just wanted to see if you might have any thought on this? 

Thanks

**Comment by vkhodygo** [comment]
Hi @pbronka 

I have some good news for you. I went through the whole codebase and got everything (sort of) fixed. 
Now labsim can run with the most recent version of jasmine. It throws some errors, but they don't look critical to me. 
The only serious issue here is related to database schemas. I thing I can create new ones with the most recent Jakarta API, but I still have no idea how to update already existing ones. 

Please, let me know what you'd like to see next.

**Comment by pbronka** [comment]
Hi @vkhodygo 

The new version of JAS-mine core loads a jamjam 0.0.1 library as dependency in the pom.xml file, but this does not seem to be available from Maven. I'm not sure what <groupId>org.uog</groupId> is. I tried to clone jamjam from your GitHub but failed; furthermore it was unclear to me which commit would be a 0.0.1 version. Could you point me in the right direction? Thanks!

**Comment by pbronka** [comment]
Hi @vkhodygo 

(I have resolved the issue above by getting by pointing JAS-mine core to a particular commit as dependency using jitpack.io to load it.

> 		<dependency>
>			<groupId>com.github.MRC-CSO-SPHSU</groupId>
>			<artifactId>jamjam</artifactId>
>			<version>38a0051</version>
>		</dependency>

I also had to replace the loading of the maven-assembly-plugin with a version from Maven's repository:

>			
>			<plugin>
>				<groupId>org.apache.maven.plugins</groupId>
>				<artifactId>maven-assembly-plugin</artifactId>
>				<version>3.3.0</version>
>			</plugin>

**However, I am now getting exactly the same problem as in the very first message in this issue:**

> Issue: DatabaseUtils from [MRC-CSO-SPHSU/JAS-mine-core/tree/dev/5.0.0](https://github.com/MRC-CSO-SPHSU/JAS-mine-core/tree/dev/5.0.0) uses SchemaExport and SchemaUpdate in the code (inputSchemaUpdateEntityManger() and getOutEntityManger(String persistenceUnitName) methods) but the imports (import org.hibernate.tool.hbm2ddl.SchemaExport; import org.hibernate.tool.hbm2ddl.SchemaUpdate) are failing.

Given that comment

>I have some good news for you. I went through the whole codebase and got everything (sort of) fixed.
Now labsim can run with the most recent version of jasmine. It throws some errors, but they don't look critical to me.

could you please provide some further instructions how to run the new version of JAS-mine core with LABSim?

**Comment by vkhodygo** [comment]
@pbronka 

>  Could you point me in the right direction?

Just clone the repo and build/install it as it is. I didn't have enough time to publish a proper release so I simply use the latest version.

> I have resolved the issue above by pointing JAS-mine core to a particular commit 

That's a nice feature I didn't know about! Thanks.

> I also had to replace the loading of the maven-assembly-plugin

I don't recall any issues with accessing this plugin, that's odd. Still, it's good you got it fixed.

> could you please provide some further instructions 

That's the thing I wanted to discuss that badly.
I think I spent at least a week reading various sources and trying different approaches, but I still have one Jakarta-related issue.
There is no `hbm2ddl` module anymore, and the release notes at the time of complete removal say there is no simple way to migrate old schema code to the new API or something. The recommendation is to ask on their forum, can't find that document though.

Nevertheless, I've updated the method to create new schemas and it seems to work. I get an error while connecting to a DB, but that's probably because I don't have a proper environment to test that.
However, I could not find any information related to schema updates. There is simply no such functionality, it's either this or my comprehension skills failed me.

I removed this part of the code to allow jasmine to build, but I didn't want to go any further than that without a proper discussion.

**Comment by pbronka** [comment]
Thanks for the clarification. My understanding of this part of the code is very limited, unfortunately. 

From what I understand, hbm2ddl was automatically generating and updating the schema based on entities in the simulation, but we will now have to find a replacement for it? (Would one option be to write the schema manually? But then we would have to update it every time something changes in the simulation?) 

Would a call (including Justin as he has more experience with the databases) be helpful to discuss how to proceed with this?

**Comment by vkhodygo** [comment]
>  `hbm2ddl` was automatically generating and updating the schema based on entities in the simulation, but we will now have to find a replacement for it? 

That's how I see it too. 
We can find a workaround for that, but I have a felling it might look like a fix. 

Yeah, I think having a call is a nice idea. Feel free to arrange a meeting any time you find convenient.

**Comment by pbronka** [comment]
Just to keep track of things, I'm closing this issue as @justin-ven updated dependencies and database code and it works as required now. These changes are on the following branch https://github.com/jasmineRepo/JAS-mine-core/tree/dev/4.0.12 and I will merge to master and do a release soon.

**Comment by vkhodygo** [comment]
@pbronka @justin-ven Apologies for the delayed reply, I was knee-deep in some issues at the  time.

This is not how it's supposed to work. I've been working on this part as well as some others too, and now we have two versions of the code that are not compatible and will require some meticulous _and_  manual intervention to merge which is what we don't need.  In addition to that, we just did essentially the same thing twice.

**Comment by pbronka** [comment]
I agree that this is not how it's supposed to work, which is why we suggested you start with a working version and help us update the libraries and database-related code as a priority and release a new working version. But this was back in June / July and we've been waiting months on what turned out to be a day of work. It is unfortunate that we had to work on the same issue but we were not able to wait any longer. 
 
Going forward we would strongly suggest that changes are small, well-tested, documented and explained, and result in a fully working version of the libraries that can be released. That way, everyone can work on some aspect of the libraries and we can ensure there is always an up-to-date working version available. 
 
If you would like to do that, please contribute to [this issue](https://github.com/jasmineRepo/JAS-mine-gui/issues/7) with the GUI and we can release a new version that fixes it.

**Comment by pbronka** [comment]
I agree that this is not how it's supposed to work, which is why we suggested you start with a working version and help us update the libraries and database-related code as a priority and release a new working version. But this was back in June / July and we've been waiting months on what turned out to be a day of work. It is unfortunate that we had to work on the same issue but we were not able to wait any longer.

Going forward we would strongly suggest that changes are small, well-tested, documented and explained, and result in a fully working version of the libraries that can be released. That way, everyone can work on some aspect of the libraries and we can ensure there is always an up-to-date working version available.

If you would like to do that, please contribute to this issue<https://github.com/jasmineRepo/JAS-mine-gui/issues/7> with the GUI and we can release a new version that fixes it.

Regards,
Patryk
