### ISSUE TITLE
Typo in RegressionUtils multinomial bootstrap

### ISSUE THREAD

**Issue by pbronka** [jasmineRepo/JAS-mine-core#5]
The method to bootstrap coefficients in case of a Multinomial Probit/Logit regression is called _boostrapMultinomialRegression_ (While for other regression models it's _bootstrap_) which seems to be a typo. If it is, I was wondering if there might be a way to change that without affecting existing models that possibly use this method?

**Comment by rer98** [comment]
Hi pbronka,
Thanks a lot for letting me know - yes, it is a typo!  I've addressed this issue by renaming the method to the correct 'bootstrapMultinomialRegression'.  I've also addressed the issue of backwards compatibility by introducing a (deprecated) method with the old name, which just calls the new method.
Many thanks again and let me know if you have any further issues!
Best wishes,
Ross

**Comment by pbronka** [comment]
Hi Ross,
That's great, thanks a lot for getting back to me so quickly and fixing it! 
Best wishes,
Patryk
